# Project configuration
name: 'book_de_project'
version: '1.0.0'
config-version: 2

# profile
profile: 'default'

# directories
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


vars:
  surrogate_key_treat_nulls_as_empty_strings: false 

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

models:
  book_de_project:
    silver:
      +materialized: view
      +database: "{{ env_var('DBT_ENVIRONMENTS', 'FAIL') }}_SILVER_LIBROS"

      goodreads:
        +schema: goodreads

      openlibrary:
        +schema: openlibrary
    gold:
      +materialized: table
      +database: "{{ env_var('DBT_ENVIRONMENTS', 'FAIL') }}_GOLD_LIBROS"

      core:
        +schema: core
      marts:
        +schema: marts