{% set edition_fields = [
    {'name': 'title', 'type': 'string'},
    {'name': 'title_prefix', 'type': 'string'},
    {'name': 'subtitle', 'type': 'string'},
    {'name': 'authors', 'type': 'variant'},
    {'name': 'other_titles', 'type': 'variant'},
    {'name': 'by_statement', 'type': 'string'},    
    {'name': 'key', 'type': 'string'},    
    {'name': 'publish_date', 'type': 'string'},
    {'name': 'copyright_date', 'type': 'string'},
    {'name': 'edition_name', 'type': 'string'},
    {'name': 'number_of_pages', 'type': 'int'},
    {'name': 'physical_dimensions', 'type': 'string'},
    {'name': 'physical_format', 'type': 'string'},
    {'name': 'description', 'type': 'string'},
    {'name': 'notes', 'type': 'string'},    
    {'name': 'languages', 'type': 'variant'},
    {'name': 'genres', 'type': 'variant'},
    {'name': 'publishers', 'type': 'variant'},
    {'name': 'identifiers', 'type': 'variant'},
    {'name': 'table_of_contents', 'type': 'variant'},
    {'name': 'work_titles', 'type': 'variant'},
    {'name': 'series', 'type': 'variant'},
    {'name': 'subjects', 'type': 'variant'},
    {'name': 'lccn', 'type': 'variant'},
    {'name': 'ocaid', 'type': 'string'},
    {'name': 'oclc_numbers', 'type': 'variant'},
    {'name': 'isbn_10', 'type': 'variant'},
    {'name': 'isbn_13', 'type': 'variant'},
    {'name': 'dewey_decimal_class', 'type': 'variant'},
    {'name': 'lc_classifications', 'type': 'variant'},
    {'name': 'contributions', 'type': 'variant'},
    {'name': 'publish_places', 'type': 'variant'},
    {'name': 'publish_country', 'type': 'string'},
    {'name': 'distributors', 'type': 'variant'},
    {'name': 'first_sentence', 'type': 'string'},
    {'name': 'weight', 'type': 'string'},
    {'name': 'location', 'type': 'variant'},
    {'name': 'scan_on_demand', 'type': 'boolean'},
    {'name': 'collections', 'type': 'variant'},
    {'name': 'uris', 'type': 'variant'},
    {'name': 'uri_descriptions', 'type': 'variant'},
    {'name': 'translation_of', 'type': 'string'},
    {'name': 'works', 'type': 'variant'},
    {'name': 'source_records', 'type': 'variant'},
    {'name': 'translated_from', 'type': 'variant'},
    {'name': 'scan_records', 'type': 'variant'},
    {'name': 'volumes', 'type': 'variant'},
    {'name': 'accompanying_material', 'type': 'string'},
    {'name': 'created', 'type': 'variant'},
    {'name': 'last_modified', 'type': 'variant'},
    {'name': 'subject_people', 'type': 'variant'},
    {'name': 'subject_place', 'type': 'variant'},
    {'name': 'subject_places', 'type': 'variant'},
    {'name': 'subject_time', 'type': 'variant'},
    {'name': 'revision', 'type': 'int'},
] 

%}

{{ generate_flatten_table(
    columna = 'raw_data',
    fields = edition_fields,
    origen = 'openlibrary',
    tabla = 'editions_raw'
) }}
